// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Thumbnail() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-[720px] aspect-video overflow-hidden\"><div id=\"template\" class=\"w-full h-full relative bg-cover overflow-hidden bg-[url(&#39;/assets/img/bg.jpg&#39;)]\"><div class=\"w-1/2 h-[200%] bg-white/90 -rotate-[15deg] translate-x-[-30px] translate-y-[-100px] absolute\"></div><div class=\"w-3/5 h-[200%] bg-white/50 -rotate-[15deg] translate-x-[-30px] translate-y-[-100px] absolute\"></div><div class=\"absolute text-slate-900 font-geist max-w-[250px] h-full m-4\"><div class=\"relative w-full h-full\"><h1 class=\"text-6xl font-semibold my-8\">One Piece</h1><p class=\"mb-4 text-2xl font-semibold border-b-2 py-4\">Rating : 99%</p><div class=\"flex flex-wrap gap-1 w-full\"><span class=\"bg-indigo-400/90 text-white px-2 rounded-full\">Anime</span> <span class=\"bg-indigo-400/90 text-white px-2 rounded-full\">Series</span> <span class=\"bg-indigo-400/90 text-white px-2 rounded-full\">Shounen</span> <span class=\"bg-indigo-400/90 text-white px-2 rounded-full\">Action</span> <span class=\"bg-indigo-400/90 text-white px-2 rounded-full\">Comedy</span></div></div><div class=\"absolute bottom-0 text-slate-900 text-sm mb-6\">POWERED BY NETFLIXIFY</div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = Base().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
